### ISSUE TITLE
[Suggestion] Option to highlight Exit, like chests.

### ISSUE THREAD

**Issue by imgidedin** [carvelli/PalacePal#13]
When doing high tier solo, it is really helpful to be able to plan ahead on your route, because we need to avoid every non-required mob and the less we need to wander around, the better.

Maybe do the same for the resurrection altar, but not sure that is really needed.

**Comment by carvelli** [comment]
I'm not really interested in having either be part of the plugin.

For what it's worth, you can trivially do this with Splatoon's layouts if you know the actor-id (these are untested, but should be the correct ids for cairn/pylon of passage, I don't have the ids for resurrection stuff). 

PotD:
```
{"Name":"Cairn of Passage","type":1,"color":3355508496,"refActorDataID":2007188,"refActorComparisonType":3}
```

HoH:
```
{"Name":"Cairn of Passage","type":1,"color":3355508496,"refActorDataID":2009507,"refActorComparisonType":3}
```

EO:
```
{"Name":"Pylon of Passage","type":1,"color":3355508496,"refActorDataID":2013287,"refActorComparisonType":3}
```
