### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by noirdove** [carvelli/PalacePal#7]
I'm sorry, I'm not that familiar with this but I can't figure out how to download/install this.  I can't find it in the Dalamud app itself and when I try this link, it just says download failed - https://github.com/carvelli/PalacePal.git.  I'm not sure if I'm trying to use the wrong address.

Any help would be greatly appreciated : )

**Comment by carvelli** [comment]
I've updated the README now, but the correct URL for the plugin repo is https://raw.githubusercontent.com/carvelli/Dalamud-Plugins/master/dist/pluginmaster.json

**Comment by noirdove** [comment]
That worked, thanks so much!
