### ISSUE TITLE
unable to load 3.1

### ISSUE THREAD

**Issue by JackieM3bs** [carvelli/PalacePal#9]
v3.1 is unable to load the plugin

[Palace Pal] Plugin could not be loaded: System.IO.FileNotFoundException - Could not find file 'C:\Users\xxx\AppData\Roaming\XIVLauncher\pluginConfigs\Palace Pal\palace-pal.config.json'.

tried reinstalling the plugin with the same error. Was working fine prior to this update!
thanks,

**Comment by asuran14** [comment]
Yes I am having the same issue

**Comment by TheNando1** [comment]
I have the same issue. Also the command /pal does now work.

**Comment by Raily-GG** [comment]
having the same issue

**Comment by Stormsinger-Frostclaw** [comment]
Also having the same issue, and it was working fine before the update.

**Comment by shaibalmuhtadee** [comment]
same issue

**Comment by carvelli** [comment]
Fixed in v3.2, please try to update & reopen the issue if the problem still exists.
